name: Continuous Delivery
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4

      - name: Simulando Continuous Delivery
        uses: actions/upload-artifact@v4
        with:
          name: produtozipado.zip
          path: |
            '**.py'
            README.md
            
  deploy:
    runs-on: ubuntu-latest
    needs: deliver
    steps:
        - uses: actions/upload-artifact@v4
          with:
            name: produtozipado.zip
            path: ''
        - name: Display structure of downloaded files
          run: ls -R


